ghostplayer:
  see-username: true
  invisible: true
  particles-apparition: true

playback:
  countdown: true
  start-second: 3

check-version: true

# A setting for a more seamless experience: see https://a5h73y.github.io/Parkour/#/guides/compatible-plugins?id=parkourghost
join_parkour_on_playback: true