ghostplayer:
  see-username: true
  invisible: true
  particles-apparition: true

playback:
  countdown: false
  start-second: 3

check-version: true

# Dev section, only change if you know what you are doing!
join_parkour_on_playback: true